### ISSUE TITLE
Auto-title function

### ISSUE THREAD

**Issue by tan3ot** [medienbaecker/kirby-modules#43]
Some sections don’t have a title, so the editor has to come up with something to make them unique.
A way to auto-generate the slugs instead of basing them on the titles would be great.
```
return [
  'medienbaecker.modules.autotitle' => true
];
```
The auto title could be maybe the timestamp? Or something like the uuid...

**Comment by medienbaecker** [comment]
I like the idea! Personally I always want to use meaningful titles/slug because that produces readable anchor links. But I can see how there can be modules where it's hard to come up with a title.

I'm a bit concerned about how the creation dialog and the module page itself will look like:

![CleanShot 2024-06-05 at 18 31 46@2x](https://github.com/medienbaecker/kirby-modules/assets/7975568/bbea6d8f-4dd7-49bf-b733-2e89f2686aca)

Putting something like the UUID or a timestamp in the big title doesn't look very nice.

**Comment by tan3ot** [comment]
Hm, that's true.

**1. Creation dialogue**
If there are multiple module templates it just could look like this:

![dialogue-without-title](https://github.com/medienbaecker/kirby-modules/assets/37336796/c17d5857-4f6c-4ca7-91f4-600f9d0a3805)

But if it's only one possible module?
Maybe just as text: "Template: Text with Images"

**2. Ugly title**
Maybe just hide the title (and the last breadcrumb item)?

Untested:
```
[data-template^="module."] .k-header-title,
[data-template^="module."] .k-breadcrumb ol li:last-child {
  display: none;
}
```

And: even if this works, this should be configurable for each modules section.
(Perhaps possible: issues after changing this behaviour later on?)

**Comment by medienbaecker** [comment]
Unfortunately this does not seem to be feasible.
